version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=$APP_PORT
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - JWT_COOKIE_EXPIRATION=$JWT_COOKIE_EXPIRATION
      - BUCKET_NAME=$BUCKET_NAME
      - BUCKET_REGION=$BUCKET_REGION
      - AWS_ACCESS_KEY=$AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
